export {
  ASSET_SCOPES,
  ASSET_TYPES,
  assetFrontmatterSchema,
  assetIdSchema,
  assetScopeSchema,
  assetTypeSchema,
  workspaceConfigSchema,
  workspaceNameSchema,
  type AssetFrontmatter,
  type AssetScope,
  type AssetType,
  type WorkspaceConfig,
} from "./schema.js";
export {
  computeContentHash,
  loadWorkspaceConfig,
  scanAssetFiles,
  scanAssetRepository,
  scanInboxRepository,
  type AssetDiagnostic,
  type AssetDiagnosticCode,
  type AssetFileScanOptions,
  type AssetScanOptions,
  type AssetScanResult,
  type ScannedAsset,
} from "./scanner.js";
export {
  AssetCatalog,
  CatalogRebuildRequiredError,
  type CatalogCounts,
  type CatalogSyncResult,
} from "./catalog.js";
export {
  AssetIndexManager,
  type AssetIndexOptions,
  type AssetIndexStatus,
  type IndexDiagnostic,
  type IndexDiagnosticSource,
  type IndexState,
  type WatcherState,
} from "./index-manager.js";
export {
  AssetNotAccessibleError,
  AssetNotFoundError,
  AssetLibraryInputError,
  AssetStaleError,
  AssetSearchInputError,
  AssetSearchService,
  AssetSearchUnavailableError,
  buildFtsAndQuery,
  escapeFtsLiteral,
  normalizeAssetSearchQuery,
  type AssetReadQuery,
  type AssetReadResult,
  type AssetLibraryItem,
  type AssetLibraryListQuery,
  type AssetLibraryListResult,
  type AssetLibraryReadResult,
  type AssetSearchContext,
  type AssetSearchDiagnostic,
  type AssetSearchDiagnosticCode,
  type AssetSearchItem,
  type AssetSearchQuery,
  type AssetSearchServiceOptions,
  type NormalizedSearchQuery,
  type SearchStrategy,
} from "./search.js";
export {
  InboxApplicationService,
  InboxUnavailableError,
  type InboxDiagnostic,
  type InboxDiagnosticCode,
  type InboxItem,
  type InboxResult,
} from "./inbox.js";
export {
  AssetConfirmationError,
  CONTENT_HASH_PATTERN,
  confirmInboxAsset,
  targetPathForInboxPath,
  type AssetConfirmationErrorCode,
  type AssetConfirmationInput,
  type AssetConfirmationOptions,
  type AssetConfirmationResult,
} from "./confirmation.js";
